### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by SJablonska** [koush/electron-chrome#15]
Hi,

Installation fails on a debian jessie system:

11474 error electron-prebuilt@1.4.6 postinstall: `node install.js`
11474 error Exit status 127
11475 error Failed at the electron-prebuilt@1.4.6 postinstall script.
11475 error This is most likely a problem with the electron-prebuilt package,
11475 error not with npm itself.
11475 error Tell the author that this fails on your system:
11475 error     node install.js
11475 error You can get their info via:
11475 error     npm owner ls electron-prebuilt
11475 error There is likely additional logging output above.
11476 error System Linux 4.8.6-040806-generic
11477 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
11478 error cwd /home/gia-admin/electron-chrome
11479 error node -v v0.10.29
11480 error npm -v 1.4.21
11481 error code ELIFECYCLE
11482 verbose exit [ 1, true ]

**Comment by danielgeraldschroeder** [comment]
I believe same issue

> electron@1.6.2 postinstall /home/dschroeder/electron-chrome/node_modules/electron
> node install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! electron@1.6.2 postinstall: `node install.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the electron@1.6.2 postinstall script.
npm ERR! This is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "electron"
npm ERR! cwd /home/dschroeder/electron-chrome
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/dschroeder/electron-chrome/npm-debug.log
npm ERR! not ok code 0

[npm-debug.log.zip](https://github.com/koush/electron-chrome/files/865087/npm-debug.log.zip)

**Comment by koush** [comment]
should be fixed, that package was deprecated.
